name: Instagram Auto-Poster

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  
  workflow_dispatch:  # Allow manual trigger from Actions tab

jobs:
  trigger-vercel-function:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Vercel Serverless Function
      run: |
        echo "🔄 Triggering Instagram post via Vercel..."
        response=$(curl -s -w "\n%{http_code}" -X GET "${{ secrets.VERCEL_FUNCTION_URL }}/api/post")
        http_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | head -n-1)
        
        echo "Response: $body"
        echo "HTTP Code: $http_code"
        
        if [ "$http_code" -eq 200 ]; then
          echo "✅ Successfully posted to Instagram!"
        else
          echo "❌ Failed to post (HTTP $http_code)"
          exit 1
        fi
