name: Keep Render Service Alive

on:
  schedule:
    # Run every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Render Service
        run: |
          echo "Pinging Render service to keep it alive..."
          curl -f https://backinsta.onrender.com/health || echo "Health check failed, service may be starting up"
          echo "Ping complete at $(date)"
